# Generated by Django 5.0.1 on 2024-09-19 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_footersettings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footersettings",
            old_name="descrition",
            new_name="description",
        ),
    ]
