# Generated by Django 5.0.1 on 2024-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_rename_descrition_footersettings_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Bailık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma tarihi"
                    ),
                ),
                (
                    "service_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="service_images/",
                        verbose_name="Hizmet Fotografı",
                    ),
                ),
            ],
        ),
    ]
